# Site settings
title: Sodadevel
email: sodadevel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 "Mobile Developer"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sodadevel.github.io" # the base hostname & protocol for your site
twitter_username: sodapanda
github_username: sodapanda

# Build settings
markdown: kramdown
